globalaccount      = "$var.globalaccount"
username           = "$var.username"
password           = "$var.password"
region             = "$var.region"
subaccount_name    = "$var.subaccount_name"
entitlement_name   = "$var.ent_name"
plan               = "$var.plan"
parent_directory   = "$tfoutputdir.directory_id.value"
