globalaccount      = "$var.globalaccount"
username           = "$var.username"
password           = "$var.password"
region             = "$var.region"
subaccount_name    = "$var.subaccount_name"
parent_directory   = "${tfoutputdir.directory_id.value}"
