globalaccount      = "$var.globalaccount"
username           = "$var.username"
password           = "$var.password"
costcenter         = "$var.costcenter"
architect          = "$var.architect"
owner              = "$var.owner"
team               = "$var.team"
parent_directory   = "$var.directory_name"
